{application,prod_test,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{prod_test_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lib_prod_test,prod_test,prod_test_app,prod_test_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
